//! Regression tests for the `Cargo.lock` integrity gate (issue #148).
//!
//! Issue #148 reported `serde_json` recording a dependency on `zmij` where
//! `ryu` was expected, and no check in this repository could tell a genuine
//! upstream rename from a substituted entry: `cargo` answers a substitution by
//! silently re-resolving the lockfile back, and under `--locked` by refusing
//! without naming a crate. `scripts/check-lockfile-integrity.sh` closes that
//! gap by comparing every recorded checksum and dependency name against the
//! manifest crates.io published for that exact version.
//!
//! Each test writes a fixture lockfile and a fixture sparse-index snapshot to a
//! temporary directory and runs the real gate against them with `--index-dir`,
//! so no test touches the network.

#![cfg(unix)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use tempfile::{TempDir, tempdir};

/// The one registry `deny.toml` allows.
const REGISTRY: &str = "registry+https://github.com/rust-lang/crates.io-index";

/// Checksums are only ever compared, never computed, so any 64-hex value
/// serves. These two are the real ones, as committed in this repository's
/// `Cargo.lock` and served by crates.io.
const CKSUM_SERDE_JSON: &str = "c841b55ecdae098c80dcae9cf767f6f8a0c2cdb3416bbef72181df4d0fe73f14";
const CKSUM_ZMIJ: &str = "29666d0abbfad1e3dc4dcf6144730dd3a3ab225bbbdac83319345b1b44ccfc1b";
const CKSUM_ITOA: &str = "1111111111111111111111111111111111111111111111111111111111111111";
const CKSUM_SUBSTITUTE: &str = "4444444444444444444444444444444444444444444444444444444444444444";

/// A lockfile and index snapshot the gate can be pointed at.
struct Fixture {
    _dir: TempDir,
    root: PathBuf,
}

impl Fixture {
    /// The baseline both fixtures start from: `serde_json` 1.0.151 exactly as
    /// crates.io publishes it — `zmij` among its built dependencies, no `ryu`,
    /// `trybuild` declared for dev only — and a lockfile that agrees with it.
    fn new() -> Self {
        let dir = tempdir().expect("tempdir");
        let root = dir.path().to_path_buf();
        fs::create_dir(root.join("index")).expect("create index dir");

        write_index(
            &root,
            "serde_json",
            &format!(
                concat!(
                    r#"{{"name":"serde_json","vers":"1.0.151","deps":["#,
                    r#"{{"name":"itoa","req":"^1.0","kind":"normal","optional":false}},"#,
                    r#"{{"name":"zmij","req":"^1.0","kind":"normal","optional":false}},"#,
                    r#"{{"name":"trybuild","req":"^1","kind":"dev","optional":false}}"#,
                    r#"],"cksum":"{}","yanked":false}}"#,
                ),
                CKSUM_SERDE_JSON
            ),
        );
        write_index(
            &root,
            "zmij",
            &format!(
                r#"{{"name":"zmij","vers":"1.0.23","deps":[],"cksum":"{CKSUM_ZMIJ}","yanked":false}}"#
            ),
        );
        write_index(
            &root,
            "itoa",
            &format!(
                r#"{{"name":"itoa","vers":"1.0.18","deps":[],"cksum":"{CKSUM_ITOA}","yanked":false}}"#
            ),
        );

        let lock = format!(
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "itoa"
version = "1.0.18"
source = "{REGISTRY}"
checksum = "{CKSUM_ITOA}"

[[package]]
name = "neat_ai_backpropagation"
version = "0.1.34"
dependencies = [
 "serde_json",
]

[[package]]
name = "serde_json"
version = "1.0.151"
source = "{REGISTRY}"
checksum = "{CKSUM_SERDE_JSON}"
dependencies = [
 "itoa",
 "zmij",
]

[[package]]
name = "zmij"
version = "1.0.23"
source = "{REGISTRY}"
checksum = "{CKSUM_ZMIJ}"
"#
        );
        fs::write(root.join("Cargo.lock"), lock).expect("write lockfile");

        Self { _dir: dir, root }
    }

    /// Rewrite the lockfile, replacing the first occurrence of `from`.
    fn edit_lock(&self, from: &str, to: &str) {
        let path = self.root.join("Cargo.lock");
        let text = fs::read_to_string(&path).expect("read lockfile");
        assert!(
            text.contains(from),
            "fixture lockfile has no '{from}' to edit"
        );
        fs::write(&path, text.replacen(from, to, 1)).expect("write lockfile");
    }

    /// Append a `[[package]]` block to the lockfile.
    fn append_lock(&self, block: &str) {
        let path = self.root.join("Cargo.lock");
        let mut text = fs::read_to_string(&path).expect("read lockfile");
        text.push_str(block);
        fs::write(&path, text).expect("write lockfile");
    }

    /// Run the real gate offline against this fixture, returning its exit code
    /// and its merged stdout and stderr.
    fn run(&self) -> (i32, String) {
        let checker = repo_root().join("scripts/check-lockfile-integrity.sh");
        let output = Command::new("bash")
            .arg(&checker)
            .arg("--lockfile")
            .arg(self.root.join("Cargo.lock"))
            .arg("--index-dir")
            .arg(self.root.join("index"))
            .output()
            .expect("run check-lockfile-integrity.sh");
        let mut merged = String::from_utf8_lossy(&output.stdout).into_owned();
        merged.push_str(&String::from_utf8_lossy(&output.stderr));
        (output.status.code().expect("exit code"), merged)
    }
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repository root")
        .to_path_buf()
}

/// One sparse-index file: the crate's name, one index JSON object per line.
fn write_index(root: &Path, crate_name: &str, line: &str) {
    fs::write(root.join("index").join(crate_name), format!("{line}\n")).expect("write index entry");
}

fn assert_outcome(code: i32, output: &str, expected_code: i32, needle: &str) {
    assert_eq!(
        code, expected_code,
        "unexpected exit code; output:\n{output}"
    );
    assert!(
        output.contains(needle),
        "output did not mention '{needle}':\n{output}"
    );
}

/// The direct answer to the finding in issue #148: `serde_json` depending on
/// `zmij` rather than `ryu` is what crates.io published, so it verifies clean.
#[test]
fn test_accepts_a_lockfile_matching_the_published_index() {
    let fixture = Fixture::new();
    let (code, output) = fixture.run();
    assert_outcome(
        code,
        &output,
        0,
        "serde_json 1.0.151: checksum and 2 dependencies match the registry",
    );
}

/// The regression test for this issue: the substitution the issue describes —
/// a real, published, correctly-checksummed crate swapped into another crate's
/// dependency list, with a `[[package]]` block of its own so every other signal
/// looks normal. Only a comparison against the upstream manifest catches it.
#[test]
fn test_rejects_a_dependency_the_published_manifest_never_declares() {
    let fixture = Fixture::new();
    write_index(
        &fixture.root,
        "wit-bindgen",
        &format!(
            r#"{{"name":"wit-bindgen","vers":"1.0.23","deps":[],"cksum":"{CKSUM_SUBSTITUTE}","yanked":false}}"#
        ),
    );
    fixture.append_lock(&format!(
        r#"
[[package]]
name = "wit-bindgen"
version = "1.0.23"
source = "{REGISTRY}"
checksum = "{CKSUM_SUBSTITUTE}"
"#
    ));
    fixture.edit_lock(" \"zmij\",\n", " \"wit-bindgen\",\n");

    let (code, output) = fixture.run();
    assert_outcome(
        code,
        &output,
        1,
        "'wit-bindgen'] that the published manifest never declares",
    );
}

/// A dev-dependency of an upstream crate is never compiled for a consumer, so
/// its presence in the consumer's lockfile is a substitution, not resolution.
#[test]
fn test_rejects_a_dependency_the_published_manifest_declares_only_for_dev() {
    let fixture = Fixture::new();
    write_index(
        &fixture.root,
        "trybuild",
        &format!(
            r#"{{"name":"trybuild","vers":"1.0.23","deps":[],"cksum":"{CKSUM_SUBSTITUTE}","yanked":false}}"#
        ),
    );
    fixture.append_lock(&format!(
        r#"
[[package]]
name = "trybuild"
version = "1.0.23"
source = "{REGISTRY}"
checksum = "{CKSUM_SUBSTITUTE}"
"#
    ));
    fixture.edit_lock(" \"zmij\",\n", " \"trybuild\",\n");

    let (code, output) = fixture.run();
    assert_outcome(code, &output, 1, "never declares");
}

/// A tampered checksum: the lockfile points at content the registry did not
/// publish under that version.
#[test]
fn test_rejects_a_checksum_that_disagrees_with_the_registry() {
    let fixture = Fixture::new();
    fixture.edit_lock(CKSUM_ZMIJ, CKSUM_SUBSTITUTE);
    let (code, output) = fixture.run();
    assert_outcome(code, &output, 1, "does not match");
}

/// An index that cannot be read is exit 2, never a pass — an unverified
/// lockfile must not look like a verified one.
#[test]
fn test_reports_a_missing_index_snapshot_with_exit_2() {
    let fixture = Fixture::new();
    fs::remove_dir_all(fixture.root.join("index")).expect("remove index dir");
    let (code, output) = fixture.run();
    assert_outcome(code, &output, 2, "index snapshot not found");
}
